apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 # tells deployment to run 1 pod matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
 apiVersion: v1
 kind: Service
 metadata:
   name: lb-nginx
   labels:
     app: nginx
 spec:
   type: LoadBalancer
   selector:
     app: utility
   ports:
   - port: 80
     targetPort: 80
     protocol: TCP 
